"""Descriptions françaises des gamerules (MC 26.1, noms snake_case).

Couche PRÉSENTATION uniquement : le domaine ne connaît pas ces textes, la
liste blanche des noms reste celle du serveur (`help gamerule`). Une règle
absente d'ici s'affiche simplement sans info-bulle — jamais bloquant, les
futures versions de Minecraft peuvent en ajouter.
"""
from __future__ import annotations

GAMERULE_HELP: dict[str, str] = {
    "advance_time": "Le cycle jour/nuit s'écoule. Désactivé : l'heure du monde est figée.",
    "advance_weather": "La météo évolue toute seule (pluie, orage). Désactivé : le temps reste fixe.",
    "allow_entering_nether_using_portals": "Les portails du Nether fonctionnent. Désactivé : impossible d'y entrer.",
    "block_drops": "Les blocs cassés laissent tomber leurs objets (minerais, bois…).",
    "block_explosion_drop_decay": "Une partie des blocs détruits par une explosion (lit, ancre) est perdue au lieu de retomber.",
    "command_block_output": "Les blocs de commande annoncent leurs actions dans le tchat.",
    "command_blocks_work": "Les blocs de commande fonctionnent. Désactivé : ils sont inertes.",
    "drowning_damage": "Les joueurs subissent des dégâts de noyade.",
    "elytra_movement_check": "Le serveur vérifie la vitesse en élytres (anti-triche). Désactiver si des joueurs légitimes sont éjectés.",
    "ender_pearls_vanish_on_death": "Les perles de l'Ender lancées disparaissent à la mort du lanceur.",
    "entity_drops": "Les entités non-créatures (objets de cadres, bateaux, minecarts…) lâchent leur contenu.",
    "fall_damage": "Les chutes infligent des dégâts.",
    "fire_damage": "Le feu et la lave infligent des dégâts.",
    "fire_spread_radius_around_player": "Rayon (en chunks) autour des joueurs où le feu se propage. 0 : le feu ne se propage jamais.",
    "forgive_dead_players": "Les créatures neutres en colère (Endermen, abeilles…) pardonnent au joueur qui meurt.",
    "freeze_damage": "La neige poudreuse inflige des dégâts de gel.",
    "global_sound_events": "Certains sons (réveil du dragon, wither…) s'entendent dans tout le monde.",
    "immediate_respawn": "Réapparition immédiate, sans écran de mort.",
    "keep_inventory": "Les joueurs gardent inventaire et expérience à la mort.",
    "lava_source_conversion": "La lave qui coule entre deux sources devient elle-même une source (comme l'eau).",
    "limited_crafting": "On ne peut fabriquer que les recettes déjà débloquées.",
    "locator_bar": "Barre de localisation des autres joueurs à l'écran.",
    "log_admin_commands": "Les commandes d'admin sont consignées dans les logs du serveur.",
    "max_block_modifications": "Nombre maximal de blocs modifiés par une seule commande (fill, clone…).",
    "max_command_forks": "Limite interne des exécutions parallèles d'une commande (execute). Ne toucher que pour des datapacks lourds.",
    "max_command_sequence_length": "Longueur maximale d'une chaîne de fonctions de commande. Ne toucher que pour des datapacks lourds.",
    "max_entity_cramming": "Nombre d'entités qui peuvent s'empiler avant de subir des dégâts d'étouffement. 0 : jamais de dégâts.",
    "max_snow_accumulation_height": "Épaisseur maximale (en couches) que la neige peut atteindre en tombant.",
    "mob_drops": "Les créatures lâchent leurs objets à la mort (viande, os…).",
    "mob_explosion_drop_decay": "Une partie des blocs détruits par une explosion de créature (creeper) est perdue.",
    "mob_griefing": "Les créatures modifient le terrain : creepers qui explosent, Endermen qui volent des blocs, moutons qui broutent…",
    "natural_health_regeneration": "La vie remonte toute seule quand la faim est suffisante.",
    "player_movement_check": "Le serveur vérifie la vitesse de déplacement (anti-triche).",
    "players_nether_portal_creative_delay": "Ticks d'attente dans un portail du Nether en créatif avant téléportation.",
    "players_nether_portal_default_delay": "Ticks d'attente dans un portail du Nether en survie avant téléportation (80 = 4 s).",
    "players_sleeping_percentage": "Pourcentage de joueurs devant dormir pour passer la nuit. 0 : un seul lit suffit ; plus de 100 : impossible.",
    "projectiles_can_break_blocks": "Les projectiles cassent les blocs fragiles (ex. flèche sur un pot décoré).",
    "pvp": "Les joueurs peuvent se blesser entre eux.",
    "raids": "Les pillards peuvent déclencher des raids sur les villages (effet Mauvais Présage).",
    "random_tick_speed": "Vitesse des événements aléatoires : pousse des cultures, feuilles, propagation du feu. 3 par défaut ; plus haut = tout pousse plus vite (et charge le serveur).",
    "reduced_debug_info": "Écran F3 appauvri pour les joueurs (masque les coordonnées).",
    "respawn_radius": "Rayon (en blocs) autour du point d'apparition du monde où les joueurs réapparaissent.",
    "send_command_feedback": "Les commandes affichent leur résultat dans le tchat de celui qui les lance.",
    "show_advancement_messages": "Les progrès des joueurs sont annoncés dans le tchat.",
    "show_death_messages": "Les messages de mort s'affichent dans le tchat.",
    "spawn_mobs": "Les créatures apparaissent naturellement (toutes catégories).",
    "spawn_monsters": "Les monstres hostiles apparaissent (zombies, squelettes…).",
    "spawn_patrols": "Des patrouilles de pillards apparaissent dans le monde.",
    "spawn_phantoms": "Des phantoms apparaissent la nuit au-dessus des joueurs qui ne dorment pas.",
    "spawn_wandering_traders": "Le marchand ambulant apparaît périodiquement.",
    "spawn_wardens": "Le Warden peut apparaître dans les Cités anciennes.",
    "spawner_blocks_work": "Les générateurs de créatures (spawners) fonctionnent.",
    "spectators_generate_chunks": "Les joueurs en mode spectateur peuvent charger de nouveaux chunks.",
    "spread_vines": "Les lianes s'étendent toutes seules sur les blocs voisins.",
    "tnt_explodes": "La TNT peut être amorcée et exploser.",
    "tnt_explosion_drop_decay": "Une partie des blocs détruits par une explosion de TNT est perdue au lieu de retomber.",
    "universal_anger": "Les créatures neutres provoquées attaquent TOUS les joueurs proches, pas seulement l'agresseur.",
    "water_source_conversion": "L'eau qui coule entre deux sources devient elle-même une source (permet les fermes à eau infinie).",
}
